baseURL = "https://jcli.jenkins-zh.cn/"
languageCode = "en-us"
title = "Jenkins CLI"
theme = "hugo-theme-learn"

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    contentDir = "content/en"
  [languages.zh]
    languageCode = "zh-CN"
    weight = 2
    languageName = "中文"
    contentDir = "content/zh"

[outputs]
home = [ "HTML", "RSS", "JSON"]
