baseURL = "http://jcli.jenkins-zh.cn/"
languageCode = "en-us"
title = "Jenkins CLI"
theme = "hugo-theme-learn"

contentDir = "content/en"
defaultContentLanguage = "en"
#defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    contentDir = "content/en"
    title = "Jenkinc CLI"
  [languages.zh]
    languageCode = "zh-CN"
    weight = 2
    languageName = "中文"
    contentDir = "content/zh"
    title = "Jenkinc CLI"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
editURL = "https://github.com/jenkins-zh/jenkins-cli-doc/blob/master/content/en/"
description = "Jenkins CLI written in golang"
showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false
