name: Deploy to GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: update
      run: |
        make theme copy-doc
    - name: gen-doc
      run: |
        curl -L https://github.com/jenkins-zh/jenkins-cli/releases/latest/download/jcli-linux-amd64.tar.gz|tar xzv
        chmod u+x jcli
        PATH=.:$PATH make gen-cmd-doc
    - name: hugo-deploy-gh-pages
      uses: jenkins-zh/hugo-gh-actions@v0.0.1
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        HUGO_VERSION: "0.53"
        WEBSITE_GIT: "git@github.com:jenkins-zh/jcli-docs.git"
        WEBSITE_DIR: "jcli-docs"
